# Generated by Django 6.0.2 on 2026-04-15 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_rename_profile_userresponse_user'),
        ('Restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsystem',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Core.restaurant'),
        ),
    ]
