# Generated by Django 6.0.2 on 2026-05-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_profile_delete_username'),
        ('Core', '0012_rename_profile_userresponse_user'),
        ('Restaurants', '0002_reviewsystem_restaurant'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewsystem',
            constraint=models.UniqueConstraint(fields=('restaurant', 'user'), name='unique_review_per_user_per_restaurant'),
        ),
    ]
