# Generated by Django 6.0.2 on 2026-03-02 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Restaruants',
            new_name='Restaurant',
        ),
    ]
