# Generated by Django 6.0.2 on 2026-03-12 07:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_rename_restaruants_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='description',
            field=models.TextField(),
        ),
    ]
