# Generated by Django 6.0.2 on 2026-03-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_alter_restaurant_options_restaurant_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
