# Generated by Django 6.0.2 on 2026-03-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0005_restaurant_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
