# Generated by Django 6.0.2 on 2026-03-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_category_restaurant_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
