# Generated by Django 6.0.2 on 2026-04-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('message_section', models.TextField()),
            ],
        ),
    ]
