# Generated by Django 6.0.2 on 2026-04-14 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_profile_delete_username'),
        ('Core', '0010_userresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Accounts.profile'),
        ),
    ]
