# Generated by Django 6.0.2 on 2026-04-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_userresponse_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresponse',
            old_name='profile',
            new_name='user',
        ),
    ]
